name: Mise à jour automatique du CAC40

on:
  schedule:
    - cron: '0 18 * * *'  # Tous les jours à 18h UTC
  workflow_dispatch:      # Permet de lancer manuellement

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          python -m pip install yfinance pandas openpyxl

      - name: Exécuter le script
        run: python projet_cac40.py

      - name: Commit et push des fichiers générés
        run: |
          git config user.name "salma741-byte"
          git config user.email "salma@example.com"
          git add CAC40_10Entreprises_Groupées.*
          git commit -m "Mise à jour automatique des données CAC40"
          git push
